SIPP
J-morag/MAPF pull request #44
Opened 2023-05-25 13:13 UTC by arbelna

Implementation of the SIPP algorithm. 
All tests passed (some asserts failed because we don't expand location as a neighboor of itself so the plan sometimes is 1 step shorter).
I also added a new test funcion to both AStar_Solver and AStarSIPP_Solver to check the running time, it looks like the runtime has dropped by about 30 percent for 6*6 map with many constrints

2023-05-30 18:58 UTC, J-morag commented
You've pushed all the commits from your previous PR into this one. Either roll them back in this PR or start a new PR with just your new changes.

2023-05-31 09:38 UTC, J-morag commented
> (some asserts failed because we don't expand location as a neighboor of itself so the plan sometimes is 1 step shorter).

This isn't good. It should comply with the exact same contract as the parent class as much as possible.

2023-05-31 10:09 UTC, J-morag requested changes
It's very cool that you've managed to implement SIPP while only changing the constraints model, and not the way a state is defined. To the best of my memory, this is not exactly how it was defined in the paper, but seems correct. I've left various comments. Please see them.
Generally, you have many code duplications from the parent class. Avoid them as much as possible. If you only need to make one or two changes to the method, try to factor out those parts of the method into new methods in the base class and then override those. It's okay to copy a method when you make many changes to it.
Finally, please run a longer experiment comparing CBS with A* and CBS with SIPP (offline, not as a new test function) and post the results on runtime and on expanded and generated low level nodes. This would also be a good opportunity to verify that you are always getting the same (optimal) solution cost. The reduction in runtime should be significant.

2023-06-05 12:20 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +    HashMap<I_Location, ArrayList<int[]>> constraintsByLocation = null;
Done

2023-06-05 12:20 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +        constraintsByLocation = constraintsToTimeIntervals(this.constraints);
Done

2023-06-05 12:22 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +        int newProblemStartTime = state.move.timeNow + 1;
Done

2023-06-05 12:22 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +    private HashMap<I_Location, ArrayList<int[]>> constraintsToTimeIntervals(ConstraintSet constraints) {
Done

2023-06-05 12:23 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +                ArrayList locationList = timeIntervals.get(timeLocation.getLocation());
Done

2023-06-05 12:24 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +            timeIntervals.put(location, new ArrayList<>(intervals));
It wasn't neccesary, removed the copy

2023-06-05 12:25 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +        // and return all constraints in timeIntervals instead of timeStamps
Done

2023-06-05 12:26 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +            intervals.add(new int[] {start, end});
I didn't know about record, I changed the data type to be record

2023-06-05 12:27 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +            }
I changed the whole function, it begins with sort (which i forgot before) and it's more efficient now

2023-06-05 12:28 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +            }
See comment above

2023-06-05 12:33 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +
Although it's really not supposed to be happened, i added a check for this in the beginning of the expand function (I guess the location in time 0 is for sure not a NO_STOP location so no need for this check in the init function)

2023-06-05 12:33 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +                    int isPossible = waitAndMove(rootState);
Done

2023-06-05 12:33 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +//                    rootState = new AStarState(possibleMove, null, problemStartTime + 2, 0);
Done

2023-06-05 12:36 UTC, arbelna commented on src/main/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_Solver.java
> +    public void expand(@NotNull AStarState state) {
Done

2023-06-05 12:52 UTC, arbelna commented on src/test/java/BasicMAPF/Solvers/AStar/SingleAgentAStar_SolverTest.java
> +        }
Done

2023-06-05 13:06 UTC, arbelna commented on src/test/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_SolverTest.java
> +    }
Done

2023-06-05 13:06 UTC, arbelna commented on src/test/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_SolverTest.java
> +
Done

2023-06-07 13:02 UTC, J-morag commented
> It's very cool that you've managed to implement SIPP while only changing the constraints model, and not the way a state is defined. To the best of my memory, this is not exactly how it was defined in the paper, but seems correct. 

I'm having second thoughts about this. I think not adding the safe interval to the sate doesn't lose correctness, but misses some of the speedup, because you're losing out on a lot of duplicate detection. 
Consider if you move from state A at t1 to B at t2. Now at state B, you see that you can get back to state A, at t3. You will generate another state, even if t3 falls within the same safe interval we came from in A. What do you think? Do you agree?
You could still finish this version and leave adding the intervals to the state to future work.

2023-06-07 16:27 UTC, arbelna commented
I think you got a point. For now I will continue with the current version
but I will think about how to implement it.

On Wed, Jun 7, 2023 at 4:02 PM J-morag ***@***.***> wrote:

> It's very cool that you've managed to implement SIPP while only changing
> the constraints model, and not the way a state is defined. To the best of
> my memory, this is not exactly how it was defined in the paper, but seems
> correct.
>
> I'm having second thoughts about this. I think not adding the safe
> interval to the sate doesn't lose correctness, but misses some of the
> speedup, because you're losing out on a lot of duplicate detection.
> Consider if you move from state A at t1 to B at t2. Now at state B, you
> see that you can get back to state A, at t3. You will generate another
> state, even if t3 falls within the same safe interval we came from in A.
> What do you think? Do you agree?
> You could still finish this version and leave adding the intervals to the
> state to future work.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/J-morag/MAPF/pull/44#issuecomment-1580772129>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWQYRGVDXMICAJWVM5BUR53XKB3WHANCNFSM6AAAAAAYO2Q4AU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-12 15:14 UTC, arbelna commented on src/test/java/BasicMAPF/Solvers/AStar/SingleAgentAStarSIPP_SolverTest.java
> +    void largeNumberOfConstraints(){
Done

2023-06-14 07:45 UTC, J-morag commented
> You've pushed all the commits from your previous PR into this one. Roll them back.

@arbelna Don't forget this.

2023-07-27 09:56 UTC, arbelna reviewed
Remove all changes related to outputStreams

2023-08-03 14:17 UTC, closed without merging